from hello_world import printfunction

printfunction("Something to print")

# __pycache__ folder is created by this folder.
# .pyc is complied python
# __pycache__ (system file autogenerated) --> source change & python version (mentioned in file)
# -> works only for imported files
# not for top level files